import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { referralApi } from '../../utils/api';
import Address from '../Address';
import { formatSUPIncome } from '../../../../utils/formatter';
import LoadingSpinner from '../LoadingSpinner';
import ErrorMessage from '../ErrorMessage';

// Component displays the referral leaderboard
const LeaderboardTab: React.FC = () => {
  const navigate = useNavigate();
  
  // State
  const [leaderboardData, setLeaderboardData] = useState<any[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedReferrer, setExpandedReferrer] = useState<string | null>(null);
  const [selectedAddresses, setSelectedAddresses] = useState<string[]>([]);
  
  // Fetch leaderboard data on component mount
  useEffect(() => {
    fetchLeaderboardData();
  }, []);
  
  // Fetch leaderboard data from API
  const fetchLeaderboardData = async () => {
    try {
      setLoading(true);
      setError(null);
      
      const response = await referralApi.getLeaderboard();
      
      if (response.success && response.data) {
        setLeaderboardData(response.data);
      } else {
        setError('Failed to load leaderboard data');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred loading leaderboard data');
    } finally {
      setLoading(false);
    }
  };
  
  // Utility function to get emoji for rank level
  const getLevelEmoji = (level: number) => {
    const emojis = ['🌱', '🌿', '🍃', '🌳', '🌴'];
    return emojis[Math.min(level - 1, emojis.length - 1)];
  };
  
  // Toggle expanded state for a referrer
  const toggleReferrerExpand = (address: string) => {
    if (expandedReferrer === address) {
      setExpandedReferrer(null);
    } else {
      setExpandedReferrer(address);
    }
  };
  
  // Handle address selection for comparison
  const handleAddressSelection = (address: string) => {
    if (selectedAddresses.includes(address)) {
      setSelectedAddresses(selectedAddresses.filter(a => a !== address));
    } else {
      if (selectedAddresses.length < 5) {  // Limit to 5 addresses
        setSelectedAddresses([...selectedAddresses, address]);
      }
    }
  };

  // Navigate to comparison page with selected addresses
  const handleCompare = () => {
    if (selectedAddresses.length > 0) {
      navigate(`/?addresses=${selectedAddresses.join(',')}`);
    }
  };

  if (loading) {
    return <div className="flex justify-center py-12"><LoadingSpinner isLoading={true} /></div>;
  }

  if (error) {
    return <ErrorMessage message={error} />;
  }

  return (
    <div className="bg-white shadow overflow-hidden sm:rounded-lg">
      <div className="px-4 py-5 sm:px-6 flex justify-between items-center">
        <div>
          <h3 className="text-lg leading-6 font-medium text-gray-900">Referral Leaderboard</h3>
          <p className="mt-1 max-w-2xl text-sm text-gray-500">Top referrers ranked by total SUP income generated by their referrals.</p>
        </div>
        <div className="flex space-x-2 items-center">
          {selectedAddresses.length > 0 && (
            <button
              onClick={handleCompare}
              className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
            >
              Compare ({selectedAddresses.length})
            </button>
          )}
        </div>
      </div>
      
      {selectedAddresses.length > 0 && (
        <div className="px-4 py-3 bg-indigo-50 border-t border-indigo-200">
          <div className="flex justify-between items-center">
            <div className="text-sm text-indigo-700">
              <span className="font-medium">{selectedAddresses.length}</span> addresses selected for comparison
            </div>
            <button
              onClick={() => setSelectedAddresses([])}
              className="text-xs text-indigo-600 hover:text-indigo-900"
            >
              Clear selection
            </button>
          </div>
        </div>
      )}
      
      {leaderboardData.length === 0 ? (
        <div className="text-center py-10 text-gray-500">
          No referrers found. Be the first to register!
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Position
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Username
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  User's SUP Income
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Referrals
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Total SUP Generated
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Avg. SUP per Referral
                </th>
                <th scope="col" className="relative px-6 py-3">
                  <span className="sr-only">Details</span>
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {leaderboardData.map((referrer, index) => (
                <React.Fragment key={referrer.address}>
                  <tr className={`${expandedReferrer === referrer.address ? 'bg-gray-50' : 'hover:bg-gray-50'} ${selectedAddresses.includes(referrer.address) ? 'bg-indigo-50' : ''}`}>
                    <td className="px-2 py-4 whitespace-nowrap text-sm font-medium">
                      <input
                        type="checkbox"
                        className="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                        checked={selectedAddresses.includes(referrer.address)}
                        onChange={() => handleAddressSelection(referrer.address)}
                        disabled={selectedAddresses.length >= 5 && !selectedAddresses.includes(referrer.address)}
                      />
                      <span className="ml-4">
                        {index + 1}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <div className="flex items-center">
                        <Address 
                          address={referrer.address} 
                          nameOverride={referrer.username}
                          showProfileIcon 
                        />
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatSUPIncome(referrer.SUPincome, 'SUP/mo')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <span className={referrer.referralCount >= referrer.maxReferrals ? "text-red-500 font-semibold" : ""}>
                        {referrer.referralCount}/{referrer.maxReferrals}
                      </span>
                      <span className="ml-2">{getLevelEmoji(referrer.level)}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatSUPIncome(referrer.totalReferralSUPincome, 'SUP/mo')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {formatSUPIncome(referrer.avgReferralSUPincome, 'SUP/mo')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <button
                        onClick={() => toggleReferrerExpand(referrer.address)}
                        className="text-indigo-600 hover:text-indigo-900"
                      >
                        {expandedReferrer === referrer.address ? 'Hide Details' : 'Show Details'}
                      </button>
                    </td>
                  </tr>
                  
                  {/* Expanded details row */}
                  {expandedReferrer === referrer.address && (
                    <tr className="bg-gray-50">
                      <td colSpan={8} className="px-6 py-4">
                        <div className="text-sm">
                          <p className="font-medium text-gray-800 mb-2">Referral Details</p>
                          
                          {referrer.referrals.length === 0 ? (
                            <p className="text-gray-500">No referrals yet</p>
                          ) : (
                            <div className="bg-white rounded border border-gray-200 overflow-hidden">
                              <table className="min-w-full divide-y divide-gray-200">
                                <thead className="bg-gray-50">
                                  <tr>
                                    <th scope="col" className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                      Address
                                    </th>
                                    <th scope="col" className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                      SUP Income
                                    </th>
                                    <th scope="col" className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                      Actions
                                    </th>
                                  </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-200">
                                  {referrer.referrals.map(referral => (
                                    <tr key={referral.address}>
                                      <td className="px-4 py-2 whitespace-nowrap text-xs text-gray-500 font-mono">
                                        <Address address={referral.address} className="text-xs" />
                                      </td>
                                      <td className="px-4 py-2 whitespace-nowrap text-xs text-gray-500">
                                        {formatSUPIncome(referral.SUPincome)}
                                      </td>
                                      <td className="px-4 py-2 whitespace-nowrap text-xs">
                                        <button
                                          className="text-xs text-indigo-600 hover:text-indigo-900"
                                          onClick={() => handleAddressSelection(referral.address)}
                                          disabled={selectedAddresses.length >= 5 && !selectedAddresses.includes(referral.address)}
                                        >
                                          {selectedAddresses.includes(referral.address) ? 'Unselect' : 'Select for Comparison'}
                                        </button>
                                      </td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            </div>
                          )}
                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default LeaderboardTab; 